CREATE TABLE tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    team INTEGER REFERENCES teams(id) NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    modified_by INTEGER REFERENCES users(id),
    date_modified TIMESTAMP DEFAULT now()
);